/* Generated from web/dashboard.html by tools/embed.sh — do not edit. */
static const char shard_ui_page[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>shard</title>\n"
"<style>\n"
":root {\n"
"  --bg: #ffffff; --panel: #f7f7f5; --line: #e2e2dd; --ink: #16161a;\n"
"  --muted: #6b6b73; --accent: #2f6f4f; --warn: #a8791b; --bad: #a83232;\n"
"  --bar: #d6d6d0;\n"
"}\n"
"@media (prefers-color-scheme: dark) {\n"
"  :root {\n"
"    --bg: #131316; --panel: #1a1a1f; --line: #2a2a31; --ink: #e8e8e6;\n"
"    --muted: #8a8a94; --accent: #6ec295; --warn: #d9ab55; --bad: #e0736b;\n"
"    --bar: #33333c;\n"
"  }\n"
"}\n"
"* { box-sizing: border-box; }\n"
"body {\n"
"  margin: 0; background: var(--bg); color: var(--ink);\n"
"  font: 14px/1.5 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;\n"
"}\n"
"header {\n"
"  display: flex; align-items: baseline; gap: 12px;\n"
"  padding: 14px 20px; border-bottom: 1px solid var(--line);\n"
"  position: sticky; top: 0; background: var(--bg); z-index: 5;\n"
"}\n"
"header h1 { font-size: 15px; margin: 0; letter-spacing: .04em; }\n"
"header .cluster { color: var(--muted); }\n"
"header .right { margin-left: auto; display: flex; gap: 10px; align-items: center; }\n"
"button {\n"
"  font: inherit; color: var(--ink); background: var(--panel);\n"
"  border: 1px solid var(--line); border-radius: 5px;\n"
"  padding: 4px 10px; cursor: pointer;\n"
"}\n"
"button:hover { border-color: var(--muted); }\n"
"main { max-width: 1100px; margin: 0 auto; padding: 22px 20px 60px; }\n"
"section { margin-bottom: 34px; }\n"
"h2 {\n"
"  font-size: 12px; text-transform: uppercase; letter-spacing: .12em;\n"
"  color: var(--muted); font-weight: 600; margin: 0 0 12px;\n"
"}\n"
".nodes { display: grid; gap: 10px; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); }\n"
".node {\n"
"  border: 1px solid var(--line); border-radius: 7px;\n"
"  background: var(--panel); padding: 12px 14px;\n"
"}\n"
".node .top { display: flex; align-items: baseline; gap: 8px; }\n"
".node .name { font-weight: 600; }\n"
".node .spec { color: var(--muted); margin-left: auto; font-size: 12px; }\n"
".dot { width: 8px; height: 8px; border-radius: 50%; display: inline-block; }\n"
".dot.online { background: var(--accent); }\n"
".dot.offline { background: var(--bar); }\n"
".tags { color: var(--muted); font-size: 12px; margin-top: 2px; }\n"
".meter { display: flex; align-items: center; gap: 8px; margin-top: 8px; font-size: 12px; }\n"
".meter .label { color: var(--muted); width: 34px; }\n"
".track { flex: 1; height: 6px; background: var(--bar); border-radius: 3px; overflow: hidden; }\n"
".fill { height: 100%; background: var(--accent); }\n"
".fill.hot { background: var(--warn); }\n"
".meter .pct { width: 40px; text-align: right; color: var(--muted); }\n"
".meter .items { color: var(--muted); white-space: nowrap; }\n"
".task .meter { margin-top: 10px; }\n"
".task .meter .label { width: 40px; }\n"
".offline-note { color: var(--muted); font-size: 12px; margin-top: 6px; }\n"
".task {\n"
"  border: 1px solid var(--line); border-radius: 7px; background: var(--panel);\n"
"  padding: 12px 14px; margin-bottom: 8px;\n"
"}\n"
".task .head { display: flex; gap: 10px; align-items: baseline; cursor: pointer; }\n"
".task .cmd { font-weight: 600; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }\n"
".task .meta { margin-left: auto; color: var(--muted); font-size: 12px; white-space: nowrap; }\n"
".status { font-size: 12px; padding: 1px 7px; border-radius: 20px; border: 1px solid var(--line); }\n"
".status.completed { color: var(--accent); }\n"
".status.running { color: var(--warn); }\n"
".status.failed, .status.timeout, .status.interrupted { color: var(--bad); }\n"
".jobs { margin-top: 10px; display: none; }\n"
".task.open .jobs { display: block; }\n"
".job {\n"
"  display: flex; align-items: center; gap: 10px;\n"
"  padding: 5px 0; border-top: 1px solid var(--line); cursor: pointer;\n"
"}\n"
".job .jname { width: 150px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }\n"
".job .jbar { flex: 1; }\n"
".job .jmeta { color: var(--muted); font-size: 12px; width: 130px; text-align: right; }\n"
"pre.log {\n"
"  margin: 8px 0 0; padding: 10px 12px; background: var(--bg);\n"
"  border: 1px solid var(--line); border-radius: 6px;\n"
"  max-height: 340px; overflow: auto; white-space: pre-wrap;\n"
"  font-size: 12.5px; color: var(--ink);\n"
"}\n"
".empty { color: var(--muted); }\n"
"footer { color: var(--muted); font-size: 12px; padding: 0 20px 30px; max-width: 1100px; margin: 0 auto; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <h1>shard</h1>\n"
"  <span class=\"cluster\" id=\"cluster-name\"></span>\n"
"  <span class=\"right\">\n"
"    <span class=\"cluster\" id=\"checked\"></span>\n"
"    <button id=\"refresh-health\">Check health</button>\n"
"  </span>\n"
"</header>\n"
"\n"
"<main>\n"
"  <section>\n"
"    <h2>Nodes</h2>\n"
"    <div class=\"nodes\" id=\"nodes\"></div>\n"
"  </section>\n"
"\n"
"  <section>\n"
"    <h2>Running</h2>\n"
"    <div id=\"running\"><p class=\"empty\">Nothing is running.</p></div>\n"
"  </section>\n"
"\n"
"  <section>\n"
"    <h2>Recent runs</h2>\n"
"    <div id=\"recent\"><p class=\"empty\">No runs yet.</p></div>\n"
"  </section>\n"
"</main>\n"
"\n"
"<footer>\n"
"  Read-only view of this cluster. Start work from the terminal:\n"
"  <code>shard exec \"uname -a\" --on all</code>\n"
"</footer>\n"
"\n"
"<script>\n"
"var open = {};          // task id -> true while its jobs are expanded\n"
"var openLog = {};       // task id -> job log file being shown\n"
"\n"
"function esc(s) {\n"
"  return String(s == null ? \"\" : s).replace(/[&<>]/g, function (ch) {\n"
"    return { \"&\": \"&amp;\", \"<\": \"&lt;\", \">\": \"&gt;\" }[ch];\n"
"  });\n"
"}\n"
"\n"
"function dur(sec) {\n"
"  sec = Number(sec) || 0;\n"
"  if (sec < 60) return sec.toFixed(1) + \"s\";\n"
"  if (sec < 3600) return Math.floor(sec / 60) + \"m \" + String(Math.floor(sec % 60)).padStart(2, \"0\") + \"s\";\n"
"  return Math.floor(sec / 3600) + \"h \" + Math.floor((sec % 3600) / 60) + \"m\";\n"
"}\n"
"\n"
"function meter(label, pct) {\n"
"  pct = Math.max(0, Math.min(100, Number(pct) || 0));\n"
"  return '<div class=\"meter\"><span class=\"label\">' + label + '</span>' +\n"
"         '<span class=\"track\"><span class=\"fill' + (pct > 75 ? \" hot\" : \"\") +\n"
"         '\" style=\"width:' + pct + '%\"></span></span>' +\n"
"         '<span class=\"pct\">' + pct + '%</span></div>';\n"
"}\n"
"\n"
"function renderNodes(cluster, health) {\n"
"  document.getElementById(\"cluster-name\").textContent =\n"
"    cluster.name + \" · \" + cluster.nodes.length + \" nodes\";\n"
"\n"
"  var checked = health && health.checked\n"
"    ? \"checked \" + new Date(health.checked * 1000).toLocaleTimeString() : \"not checked yet\";\n"
"  document.getElementById(\"checked\").textContent = checked;\n"
"\n"
"  var html = cluster.nodes.map(function (n) {\n"
"    var h = (health && health.nodes && health.nodes[n.name]) || null;\n"
"    var online = h && h.status === \"online\";\n"
"    var spec = [];\n"
"    if (n.cpu) spec.push(n.cpu + \" CPU\");\n"
"    if (n.ram_gb) spec.push(n.ram_gb + \" GB\");\n"
"    if (online && !n.cpu && h.ncpu) spec.push(h.ncpu + \" CPU\");\n"
"\n"
"    var body = \"\";\n"
"    if (online) {\n"
"      body = meter(\"cpu\", h.cpu_pct) + meter(\"ram\", h.ram_pct);\n"
"    } else if (h) {\n"
"      body = '<p class=\"offline-note\">' + esc(h.error || \"offline\") + \"</p>\";\n"
"    } else {\n"
"      body = '<p class=\"offline-note\">no health data — press Check health</p>';\n"
"    }\n"
"\n"
"    return '<div class=\"node\"><div class=\"top\">' +\n"
"      '<span class=\"dot ' + (online ? \"online\" : \"offline\") + '\"></span>' +\n"
"      '<span class=\"name\">' + esc(n.name) + \"</span>\" +\n"
"      '<span class=\"spec\">' + esc(spec.join(\" · \")) + \"</span></div>\" +\n"
"      '<div class=\"tags\">' + esc(n.host) + (n.tags.length ? \"  [\" + esc(n.tags.join(\", \")) + \"]\" : \"\") + \"</div>\" +\n"
"      body + \"</div>\";\n"
"  }).join(\"\");\n"
"\n"
"  document.getElementById(\"nodes\").innerHTML = html ||\n"
"    '<p class=\"empty\">No nodes in cluster.toml yet.</p>';\n"
"}\n"
"\n"
"function jobRow(task, j) {\n"
"  var pct = j.status === \"completed\" ? 100 : (j.status === \"running\" ? 50 : 100);\n"
"  var cls = j.status === \"running\" ? \"\" : (j.status === \"completed\" ? \"\" : \"hot\");\n"
"  return '<div class=\"job\" data-task=\"' + esc(task.id) + '\" data-log=\"' + esc(j.log) + '\">' +\n"
"    '<span class=\"jname\">' + esc(j.label) + \"</span>\" +\n"
"    '<span class=\"jbar\"><span class=\"track\"><span class=\"fill ' + cls +\n"
"    '\" style=\"width:' + pct + '%\"></span></span></span>' +\n"
"    '<span class=\"status ' + esc(j.status) + '\">' + esc(j.status) + \"</span>\" +\n"
"    '<span class=\"jmeta\">' + dur(j.duration) +\n"
"    (j.exit > 0 ? \" · exit \" + j.exit : \"\") + \"</span></div>\";\n"
"}\n"
"\n"
"// A run made of items reports its real progress; one made of whole jobs\n"
"// counts the jobs that have finished.\n"
"function progressRow(t) {\n"
"  if (!t.items_total) return \"\";\n"
"  var pct = Math.round((t.items_done / t.items_total) * 100);\n"
"  var eta = \"\";\n"
"  if (t.status === \"running\" && t.items_done > 0) {\n"
"    var per = t.duration / t.items_done;\n"
"    eta = \" · about \" + dur(per * (t.items_total - t.items_done)) + \" left\";\n"
"  }\n"
"  return '<div class=\"meter\"><span class=\"label\">' + pct + '%</span>' +\n"
"    '<span class=\"track\"><span class=\"fill\" style=\"width:' + pct + '%\"></span></span>' +\n"
"    '<span class=\"items\">' + t.items_done + \" / \" + t.items_total + \" items\" +\n"
"    (t.items_failed ? \" · \" + t.items_failed + \" failed\" : \"\") + eta + \"</span></div>\";\n"
"}\n"
"\n"
"function taskCard(t) {\n"
"  var done = t.jobs.filter(function (j) { return j.status !== \"running\" && j.status !== \"pending\"; }).length;\n"
"  var isOpen = open[t.id];\n"
"  var logFile = openLog[t.id];\n"
"  var counted = t.items_total\n"
"    ? t.items_done + \"/\" + t.items_total + \" items\"\n"
"    : done + \"/\" + t.jobs.length;\n"
"\n"
"  return '<div class=\"task' + (isOpen ? \" open\" : \"\") + '\" data-id=\"' + esc(t.id) + '\">' +\n"
"    '<div class=\"head\"><span class=\"status ' + esc(t.status) + '\">' + esc(t.status) + \"</span>\" +\n"
"    '<span class=\"cmd\">' + esc(t.command) + \"</span>\" +\n"
"    '<span class=\"meta\">' + counted + \" · \" + dur(t.duration) +\n"
"    \" · \" + esc(t.started_at) + \"</span></div>\" +\n"
"    progressRow(t) +\n"
"    '<div class=\"jobs\">' + t.jobs.map(function (j) { return jobRow(t, j); }).join(\"\") +\n"
"    (logFile ? '<pre class=\"log\" id=\"log-' + esc(t.id) + '\">loading…</pre>' : \"\") +\n"
"    \"</div></div>\";\n"
"}\n"
"\n"
"function renderTasks(tasks) {\n"
"  var running = tasks.filter(function (t) { return t.status === \"running\"; });\n"
"  var recent = tasks.filter(function (t) { return t.status !== \"running\"; });\n"
"\n"
"  document.getElementById(\"running\").innerHTML =\n"
"    running.length ? running.map(taskCard).join(\"\") : '<p class=\"empty\">Nothing is running.</p>';\n"
"  document.getElementById(\"recent\").innerHTML =\n"
"    recent.length ? recent.map(taskCard).join(\"\") : '<p class=\"empty\">No runs yet.</p>';\n"
"\n"
"  Object.keys(openLog).forEach(function (id) { loadLog(id, openLog[id]); });\n"
"}\n"
"\n"
"function loadLog(id, file) {\n"
"  var pre = document.getElementById(\"log-\" + id);\n"
"  if (!pre) return;\n"
"  fetch(\"/api/log?id=\" + encodeURIComponent(id) + \"&file=\" + encodeURIComponent(file) + \"&tail=400\")\n"
"    .then(function (r) { return r.text(); })\n"
"    .then(function (text) {\n"
"      var atBottom = pre.scrollTop + pre.clientHeight >= pre.scrollHeight - 20;\n"
"      pre.textContent = text || \"(no output)\";\n"
"      if (atBottom) pre.scrollTop = pre.scrollHeight;\n"
"    });\n"
"}\n"
"\n"
"document.addEventListener(\"click\", function (ev) {\n"
"  var job = ev.target.closest(\".job\");\n"
"  if (job) {\n"
"    var id = job.dataset.task;\n"
"    openLog[id] = openLog[id] === job.dataset.log ? null : job.dataset.log;\n"
"    if (!openLog[id]) delete openLog[id];\n"
"    refresh();\n"
"    return;\n"
"  }\n"
"  var head = ev.target.closest(\".task .head\");\n"
"  if (head) {\n"
"    var tid = head.closest(\".task\").dataset.id;\n"
"    if (open[tid]) { delete open[tid]; delete openLog[tid]; }\n"
"    else open[tid] = true;\n"
"    refresh();\n"
"  }\n"
"});\n"
"\n"
"document.getElementById(\"refresh-health\").addEventListener(\"click\", function () {\n"
"  var b = this;\n"
"  b.disabled = true;\n"
"  b.textContent = \"Checking…\";\n"
"  fetch(\"/api/health\", { method: \"POST\" })\n"
"    .then(function () { return refresh(); })\n"
"    .finally(function () { b.disabled = false; b.textContent = \"Check health\"; });\n"
"});\n"
"\n"
"function refresh() {\n"
"  return Promise.all([\n"
"    fetch(\"/api/cluster\").then(function (r) { return r.json(); }),\n"
"    fetch(\"/api/health\").then(function (r) { return r.json(); }),\n"
"    fetch(\"/api/tasks?limit=25\").then(function (r) { return r.json(); })\n"
"  ]).then(function (res) {\n"
"    renderNodes(res[0], res[1]);\n"
"    renderTasks(res[2].tasks);\n"
"  }).catch(function (e) {\n"
"    document.getElementById(\"cluster-name\").textContent = \"connection lost\";\n"
"  });\n"
"}\n"
"\n"
"refresh();\n"
"setInterval(refresh, 2000);\n"
"</script>\n"
"</body>\n"
"</html>\n"
;
